spring:
  redis:
    database: 0 # redis数据库
    host: 127.0.0.1 # redis服务器地址
    port: 6379 # redis服务器连接端口
    timeout: 5s # 连接超时时间
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时机(-1表示没限制)
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接

aliyun: #接入阿里云 (发送验证码短信)
  accessKeyId: LTAI5tGX3bJfafPdrrC7uwrU
  accessKeySecret: 4qvGDqwNelzyR3Ezk2yxavcahS3Amj