server:
  port: 8081

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

storage:
  type: minio # 对象存储类型（目前可选 minio, aliyun）
  bucket: linker # 对象存储 bucket name