spring:
  redis:
    database: 0 # redis数据库
    host: 127.0.0.1 # redis服务器地址
    port: 6379 # redis服务器连接端口
    timeout: 5s # 连接超时时间
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时机(-1表示没限制)
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接信息
    url: jdbc:mysql://localhost:3306/linker?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: linker_manager
    # 私钥加密后的密码
    password: H0jyWPSS8YgJKCPXk5W9a3twKIzSxAp4uJE99rRkkly/Gypz9JZCnI470jDs5om/cZtceHvAEF8xmUBtw1+2XA==
    druid: # druid连接池配置
      initial-size: 5 # 初始大小
      min-idle: 5 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 60000 # 连接时最大等待时间
      test-while-idle: true # 空闲时是否执行检查
      time-between-eviction-runs-millis: 60000 # 多久进行一次检测
      min-evictable-idle-time-millis: 300000 # 一个连接的最小生存时间
      max-evictable-idle-time-millis: 900000 # 一个连接的最大生存时间
      validation-query: SELECT 1 FROM DUAL # 测试连接是否可用的SQL
      test-on-borrow: false # 从连接池获取连接时是否检测可用性（影响性能）
      test-on-return: false # 连接返回连接池时是否检测可用性
      pool-prepared-statements: false # 是否缓存prepared-statements
      web-stat-filter:
        enabled: true # 开启web监控
      stat-view-servlet: # 配置后台监控服务
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
      # 配置解密公钥
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJj0nuclDUrsGwKl3ZRuR/X1PU9FwHSNcHJYulf6W8SztKry/daK7M7UOAep1qLsYMQ8DdMwk1BS1p7cKxJse0ECAwEAAQ==
      filter: # 配置druid过滤器
        config:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true # 排查慢SQL
          slow-sql-millis: 2000 # 超过2s的都算慢SQL
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true